version: "3.8"
services:
  api-tests:
    image: debasmita25/github-api-tests
    container_name: api-tests-runner
    environment:
      JENKINS_MODE: "true"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      TEST_SUITE: ${TEST_SUITE}
      TEST_ENV: ${TEST_ENV}
    volumes:
      - ./allure-results:/home/api-docker/allure-results
      - ./allure-report:/home/api-docker/allure-report
    restart: "no"    

  # flight-reservation:
  #   image: debasmita25/selenium-tests-grid:1.0.8
  #   environment:
  #   - BROWSER=${BROWSER}
  #   - HUB_HOST=hub
  #   - THREAD_COUNT=3
  #   - TEST_SUITE=flight-reservation.xml
  #   - TEST_ENV=qa
  #   volumes:
  #   - ./output/${BROWSER}/flight-reservation/results:/home/selenium-docker/test-output
  #   - ./output/${BROWSER}/flight-reservation/container-logs:/home/selenium-docker/logs



  # flight-reservation:
  #   image: debasmita25/selenium-tests-grid:1.0.2
  #   depends_on:
  #   - firefox
  #   environment:
  #   - BROWSER=firefox
  #   - HUB_HOST=hub
  #   - THREAD_COUNT=2
  #   - TEST_SUITE=flight-reservation.xml
  #   volumes:
  #   - G:\eclipse-workspace\webdocker\output\flight-reservation\results:/home/selenium-docker/test-output
  #   - G:\eclipse-workspace\webdocker\output\flight-reservation\container-logs:/home/selenium-docker/logs
